---
url: http://tonyarnold.com
title: tonyarnold.com
exclude:
- LICENSE
- CNAME
- README.md
- ".gitignore"
- Gemfile
- Gemfile.lock
- ".ruby-version"
- ".ruby-gemset"
- ".DS_Store"
timezone: Australia/NSW
future: false
markdown: kramdown
lsi: false
kramdown:
  input: GFM
sass:
  sass_dir: assets/css/_scss
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
theme_settings:
  highlight_color: "#990000"
  social:
    github: tonyarnold
    bitbucket: tonyarnold
    flickr: tonyarnold
    twitter: tonyarnold
  name: Tony Arnold
  email: tony@tonyarnold.com
  tagline: readwrite, nonnull, nonatomic, strong
  google_analytics_key: UA-87298-13
  show_disclaimer: false
prose:
  ignore:
  - "/.gitignore"
  - "/.ruby-gemset"
  - "/.ruby-version"
  - "/_config.yml"
  - "/_layouts"
  - "/_includes"
  - "/_scss"
  - "/assets"
  - "/atom.xml"
  - "/CNAME"
  - "/favicon.*"
  - "/Gemfile"
  - "/Gemfile.lock"
  - "/index.*"
  - "/LICENSE"
  - "/site.json"
  - "/links.jsonp"
  rooturl: ''
  siteurl: http://tonyarnold.com'
  relativeLinks: http://tonyarnold.com/links.jsonp
  media: assets/media
  metadata:
    '':
    - name: layout
      field:
        element: hidden
        value: default
    - name: title
      field:
        element: text
        label: Title
        value: ''
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: date
      field:
        element: text
        label: Date
        placeholder: eg. 27 March 2014 10:32:29
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        alterable: true
        options:
        - name: Cocoa
          value: Cocoa
        - name: Entertainment
          value: Entertainment
        - name: Life
          value: Life
        - name: Mac
          value: Mac
        - name: Programming
          value: Programming
        - name: Web
          value: Web
        - name: Work
          value: Work
        - name: WWDC
          value: WWDC
    - name: source
      field:
        element: text
        label: Source URL
        value: ''
