# General Jekyll Config
url: http://tonyarnold.com
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, .ruby-version, .ruby-gemset, .DS_Store]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Australia/NSW
future: false
markdown: kramdown
highlighter: rouge
lsi: true

sass:
    sass_dir: _scss

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#990000'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: tonyarnold
    bitbucket: tonyarnold
    flickr: tonyarnold
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    #adn: tonyarnold
    twitter: tonyarnold
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 109897301214575359936

  # "Hi, I'm _______"
  name: Tony Arnold
  email: tony@tonyarnold.com
  tagline: "readwrite, nonatomic, strong"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-87298-13

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false


prose:
  ignore:
  - /.gitignore
  - /.ruby-gemset
  - /.ruby-version
  - /_config.yml
  - /_layouts
  - /_includes
  - /assets
  - /atom.xml
  - /CNAME
  - /favicon.*
  - /Gemfile
  - /Gemfile.lock
  - /index.*
  - /LICENSE
  - /site.json
  - /links.jsonp
  rooturl: ''
  siteurl: http://tonyarnold.com'
  relativeLinks: 'http://tonyarnold.com/links.jsonp'
  media: 'assets/media'
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          placeholder: "eg. 27 March 2014 10:32:29"
      - name: "tags"
        field:
        element: "multiselect"
        label: "Add Tags"
        placeholder: "Choose Tags"
        options:
        - name: "Cocoa"
          value: "Cocoa"
        - name: "Entertainment"
          value: "Entertainment"
        - name: "Life"
          value: "Life"
        - name: "Mac"
          value: "Mac"
        - name: "Programming"
          value: "Programming"
        - name: "Web"
          value: "Web"
        - name: "Work"
          value: "Work"
        - name: "WWDC"
          value: "WWDC"
